default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username:
  password:

development: &development
  <<: *default
  database: consul_development

test:
  <<: *default
  database: consul_test

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

preproduction:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
